# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 23:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCracha', models.CharField(max_length=200, verbose_name='Nome para crachá')),
                ('instituicao', models.CharField(max_length=200, verbose_name='Instituição')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('municipio', models.CharField(max_length=20, verbose_name='Município')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('status', models.IntegerField()),
                ('codigoConfirmacao', models.CharField(max_length=200, verbose_name='Codigo de confirmação')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
