# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='codigoConfirmacao',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='status',
        ),
    ]
