# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mesa', '0001_initial'),
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('status_pedido', models.IntegerField(choices=[(1, 'Aguardando'), (2, 'Em Andamento'), (3, 'Pronto'), (4, 'Entregue')], default=1)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mesa.Mesa')),
                ('produtos', models.ManyToManyField(to='produto.Produto')),
            ],
        ),
    ]
