# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='codigo',
        ),
    ]
