# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('participante', '0001_initial'),
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='participante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='participante.Participante'),
            preserve_default=False,
        ),
    ]
