# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0002_remove_inscricao_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='homologada',
        ),
    ]
