# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
        ('participante', '0001_initial'),
        ('inscricao', '0003_remove_inscricao_homologada'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inscricao',
            unique_together=set([('evento', 'participante')]),
        ),
    ]
