# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_auto_20170503_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='ativa',
            new_name='credenciado',
        ),
    ]
