# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('numero', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('status', models.IntegerField(choices=[(0, 'Fechada'), (1, 'Aberta')], default=0)),
            ],
        ),
    ]
