# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160803171240 on 2017-02-27 03:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('imageFile', models.ImageField(upload_to='produto/imagens')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_produto', models.IntegerField(choices=[(1, 'Bebida'), (2, 'Lanche')], default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
