# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160803171240 on 2016-11-29 21:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='cpf_invalido', message='Verifique o CPF', regex='^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d-\\d\\d$')])),
                ('curso', models.CharField(max_length=100)),
                ('dataNascimento', models.DateField()),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtdAtletas', models.PositiveIntegerField()),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('atletas', models.ManyToManyField(to='esporte.Atleta')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=200)),
                ('dataInicio', models.DateField(blank=True)),
                ('dataFim', models.DateField(blank=True)),
                ('tipo', models.SmallIntegerField(choices=[(1, 'NACIONAL-UNIVERSTARIO'), (2, 'ESTADUAL-UNIVERSTARIO'), (3, 'REGIONAL-UNIVERSTARIO'), (4, 'NACIONAL'), (5, 'ESTADUAL'), (6, 'REGIONAL'), (7, 'OUTRO')])),
                ('equipes', models.ManyToManyField(to='esporte.Atleta')),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('endereco', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('quantidade', models.PositiveIntegerField()),
                ('patrimonio', models.PositiveIntegerField(blank=True)),
                ('descricao', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('qtdMaxAtletas', models.PositiveIntegerField(blank=True)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(code='cpf_invalido', message='Verifique o CPF', regex='^\\d\\d\\d\\.\\d\\d\\d\\.\\d\\d\\d-\\d\\d$')])),
                ('crefi', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='modalidades',
            field=models.ManyToManyField(to='esporte.Modalidade'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='modalidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esporte.Modalidade'),
        ),
    ]
