# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('imageFile', models.ImageField(upload_to='produto')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('tipo_produto', models.IntegerField(choices=[(1, 'Bebida'), (2, 'Bebida Alcoolica'), (3, 'Refeições'), (4, 'Sobremesas')], default=1)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Preço')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='imagem',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produto.Produto'),
        ),
    ]
