# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do evento')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('local', models.CharField(max_length=200, verbose_name='Local')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('numeroVagas', models.IntegerField(verbose_name='Número de Vagas')),
                ('dataInicio', models.DateField(verbose_name='Data de Início')),
                ('dataFim', models.DateField(verbose_name='Data de Fim')),
            ],
        ),
    ]
