# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_programacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='numeroInscritos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='programacao',
            name='descricao',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programacao',
            name='dataFim',
            field=models.DateField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='programacao',
            name='dataInicio',
            field=models.DateField(verbose_name='Início'),
        ),
    ]
