# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20170516_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacao',
            name='dataFim',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='programacao',
            name='dataInicio',
            field=models.DateTimeField(verbose_name='Início'),
        ),
    ]
